# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Storage X\About\IT\Python\Git\AUser\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setStyleSheet("#cw {\n"
"    background-color: rgba(22, 8, 23, 200);\n"
"}\n"
"QStatusBar {\n"
"    background-color: rgb(22, 8, 23);\n"
"    border: 1px solid rgb(255, 200, 200);\n"
"    color: rgb(255, 200, 200);\n"
"}\n"
"QListWidget {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 200, 200);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 200, 200, 150);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 200, 200, 100);\n"
"}")
        self.cw = QtWidgets.QWidget(MainWindow)
        self.cw.setObjectName("cw")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cw)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lW = QtWidgets.QListWidget(self.cw)
        self.lW.setObjectName("lW")
        self.verticalLayout.addWidget(self.lW)
        self.btn_on = QtWidgets.QPushButton(self.cw)
        self.btn_on.setMinimumSize(QtCore.QSize(282, 20))
        self.btn_on.setObjectName("btn_on")
        self.verticalLayout.addWidget(self.btn_on)
        self.btn_off = QtWidgets.QPushButton(self.cw)
        self.btn_off.setMinimumSize(QtCore.QSize(282, 20))
        self.btn_off.setObjectName("btn_off")
        self.verticalLayout.addWidget(self.btn_off)
        MainWindow.setCentralWidget(self.cw)
        self.sB = QtWidgets.QStatusBar(MainWindow)
        self.sB.setObjectName("sB")
        MainWindow.setStatusBar(self.sB)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AUser"))
        self.btn_on.setText(_translate("MainWindow", "Включить"))
        self.btn_off.setText(_translate("MainWindow", "Выключить"))
